public class Datetime_Assignment {
    public void diffofDate(){
        Date varTomorrowDate = date.newInstance(2022, 11, 17);
        Date varTodaysDate = date.newInstance(2022, 11, 16);
        integer difference = varTomorrowDate.daysBetween(varTodaysDate);
        system.debug('The days difference is: ' + difference);

    }
    public void Timecheck(){
        Datetime varTomorrowDatetime = datetime.newInstance(2022, 11, 17, 7, 0, 0);
        Datetime var10DaysDatetime = datetime.newInstancegmt(2022, 11, 27, 9, 0 0);
        Long varDatetimeLong = 
    }
}
