public class StudentDetails {
    public void Nameofstudent(){
        string name = 'Elif';
        system.debug('Name of student: ' + name);
        string placeofBirth = 'Istanbul';
        system.debug('Place of birth: ' + placeofBirth);
        string hobbies = 'movies, cooking, hiking, tennis,painting';
        system.debug('Things you like: ' + hobbies);
        string places = 'NYC, San Francisco, Philadelphia';
        system.debug('Places you like to visit: ' + places);

    }
}
