returnArithmaticalcalculations son = new returnArithmaticalcalculations();
integer sum1 = son.Addition(5,7);
system.debug('Sum1--> ' + sum1);
integer sum2 = son.Addition(6, 8);
system.debug('Sum 2--> ' + sum2);

returnArithmaticalcalculations s1 = new returnArithmaticalcalculations();
integer sumo1 = s1.Addition(7, 9, 3, 2);
system.debug('Result is ' + sumo1);
integer sumo2 = s1.Addition(9, 9, 5, 1);
system.debug('Result is ' + sumo2);

